# Imagen base de Nginx (servidor web ligero)
FROM nginx:alpine

# Copiar el archivo HTML al directorio de Nginx
COPY index.html /usr/share/nginx/html/index.html

# Exponer el puerto 80 (puerto por defecto de Nginx)
EXPOSE 80

# Nginx inicia automáticamente con la imagen
